# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' mat2DF
#'
#' A function that converts a matrix to data frame
#'
#' @param x a matrix to be converted into a data frame
#'
#' @return x converted to a data frame
#'
mat2DF <- function(x) {
    .Call(`_remx_mat2DF`, x)
}

#' rehPoisson
#'
#' A function that reshapes the data set to allow implementation of the REM writen as Poisson regression
#'
#' @param stats a remstats object, the objects inside the list must be in the same order as they would be in remstats
#'
#' @return a data frame with events stacked
#'
rehPoisson <- function(stats) {
    .Call(`_remx_rehPoisson`, stats)
}

#' burnInRows
#'
#' A function that applies row-wise burn-in to the MCMC samples
#'
#' @param Nthin number of samples to skip before keeping one MCMC sample
#' @param Nburn number of samples to discard at the beginning of the chain
#' @param samples a 3-d array containing MCMC samples
#'
#' @return 3-d array with altered dimension, leaving out Nburn samples and keeping one out of every Nthin
#'
burnInRows <- function(Nthin, Nburn, samples) {
    .Call(`_remx_burnInRows`, Nthin, Nburn, samples)
}

#' burnInSlices
#'
#' A function that applies slice-wise burn-in to the MCMC samples
#'
#' @param Nthin number of samples to skip before keeping one MCMC sample
#' @param Nburn number of samples to discard at the beginning of the chain
#' @param samples a 3-d array containing MCMC samples
#'
#' @return 3-d array with altered dimension, leaving out Nburn samples and keeping one out of every Nthin
#'
burnInSlices <- function(Nthin, Nburn, samples) {
    .Call(`_remx_burnInSlices`, Nthin, Nburn, samples)
}

#' rndMeans
#' This function only returns the components of the fixed effects that are random effects means
#'@param x matrix specifying which parameters are to be extracted from the vector
#'@param psi a vector containing fixed- and random-effects estimates
rndMeans <- function(x, psi) {
    .Call(`_remx_rndMeans`, x, psi)
}

#' UpdateBeta
#'
#' A function to update the group specific parameters of the multilevel model
#'
#' @param p an integer that determines the dimension of the vector of parameters in each group
#' @param K an integer representing the number of groups in the analysis
#' @param beta_hat a matrix with dimensions p x K representing the MLE estimates for each independent groups
#' @param omega_hat a 3-d array with dimensions p x p x K representing the covariance matrix of the MLEs
#' @param Mu a vector p x 1 representing the mean of the random effects
#' @param Sigma a matrix p x p representing the covariance matrix of the random effects
#'
#' @return a matrix with dimensions p x K representing one sample of the posterior distribution of the beta
#'
UpdateBeta <- function(p, K, beta_hat, omega_hat, Mu, Sigma) {
    .Call(`_remx_UpdateBeta`, p, K, beta_hat, omega_hat, Mu, Sigma)
}

#' UpdateOmega
#'
#' A function to update the scale mixture variable that allows beta to have a student-t likelihood
#'
#' @param p an integer that determines the dimension of the vector of parameters in each group
#' @param K an integer representing the number of groups in the analysis
#' @param beta_hat a matrix with dimensions p x K representing the MLE estimates for each independent groups
#' @param omega_hat a 3-d array with dimensions p x p x K representing the covariance matrix of the MLEs
#' @param Mu a vector with dimension p representing the random-effect means
#' @param Sigma a matrix p x p representing the covariance matrix of the random effects
#' @param nu a vector of dimension K representing the degress of freedom of the student-t distribution for each group
#' @param beta a matrix with dimensions p x K representing one MCMC sample of the group-specific parameters, aka random effects
#'
#' @return a vector with dimension K representing one MCMC sample of the scale mixture variable omega
#'
UpdateOmega <- function(p, K, beta_hat, omega_hat, Mu, Sigma, nu, beta) {
    .Call(`_remx_UpdateOmega`, p, K, beta_hat, omega_hat, Mu, Sigma, nu, beta)
}

#' UpdateMu
#'
#' A function to update the vector of random-effect means
#' @param p an integer representing the number of random effects in the model
#' @param K is the number of groups in the multilevel analysis
#' @param TauMu is a matrix with dimensions p x p representing the covariance matrix of the prior of Mu
#' @param Sigma is a p x p matrix representing the covariance matrix of the random effects
#' @param beta is a p x K matrix representing one MCMC sample of the p random effects for each of the K groups
#'
#' @return a matrix with dimensions 1 x p representing one MCMC sample of the random-effect mean vector
#'
UpdateMu <- function(p, K, TauMu, Sigma, beta) {
    .Call(`_remx_UpdateMu`, p, K, TauMu, Sigma, beta)
}

#' UpdateSigma
#'
#' A function to update the covariance matrix of the random effects, for details see Huang & Wand (2013)
#'
#' @param eta an integer representing a prior hyperparameter, this will allow Sigma to have a Half-t prior
#' @param K an integer representing the number of groups
#' @param p an integer representing the number of the covariates in the models, Sigma in the end will have dimensions p x p
#' @param Lambda a vector with dimension p, this is an auxiliary variable that allows Sigma to have a Half-t prior
#' @param beta is a matrix with dimensions p x K representing one MCMC sample of the random effects
#'
#' @return a p x p matrix representing one MCMC sample of the covariance matrix of the random effects
#'
UpdateSigma <- function(eta, K, p, Lambda, beta) {
    .Call(`_remx_UpdateSigma`, eta, K, p, Lambda, beta)
}

#' UpdateLambda
#'
#' A function to update the mixture parameters that allow Sigma to have a Halt-t prior, see Huang & Wand (2013)
#'
#' @param p an integer denoting the dimension of the covariance matrix Sigma
#' @param eta an integer that we set equal to 2, so the covariances have an uniform prior, see Huang & Wand (2013)
#' @param Sigma a p x p matrix representing one MCMC sample of the random-effect covariance matrix
#' @param xi a scalar that can be an arbitrarily large number, see Gelman (2006)
#'
#' @return a row vector representing one MCMC sample of the mixture parameter that allows the covariance matrix of the random effects to have a Half-t prior
#'
UpdateLambda <- function(p, eta, Sigma, xi) {
    .Call(`_remx_UpdateLambda`, p, eta, Sigma, xi)
}

#' UpdatePsi
#'
#' A function that updates the fixed-effect parameters in the mixed-effect relational event model
#'
#' @param q an integer representing the number of fixed effects in the model
#' @param K an integer representing the number of groups (or networks) in the multilevel analysis
#' @param TauPsi a vector of dimension q, which represents the prior variance of the fixed effects
#' @param SigmaPsi a matrix with dimensions q x K representing the standard errors of the MLEs for the fixed effects
#' @param psi a matrix with dimensions q x K representing the MLEs for the fixed effects independently estimated from every group
#'
#' @return a row vector with dimension q representing one MCMC sample of the fixed effects
#'
UpdatePsi <- function(q, K, TauPsi, SigmaPsi, psi) {
    .Call(`_remx_UpdatePsi`, q, K, TauPsi, SigmaPsi, psi)
}

#'UpdateMean
#'This is a new function that models fixed-effects and random-effects means together so we do not ignore their dependency
#'This function already does what we want
#'
#' @param q number of fixed effects
#' @param p number of random effects
#' @param K number of networks
#' @param SigmaMean covariance matrices of the MLE estimates
#' @param psi MLE estimates
#' @param delta random-effects estimates
#' @param randomModel boolean, if TRUE model contains random effects
UpdateMean <- function(q, p, K, SigmaMean, psi, delta, randomModel) {
    .Call(`_remx_UpdateMean`, q, p, K, SigmaMean, psi, delta, randomModel)
}

#'UpdateDelta
#'This is the function that samples the random effects
#'
#'@param q number of fixed effects
#'@param p number of random effects
#'@param K number of networks
#'@param beta_hat MLE estimates
#'@param Mu mean of the random effects
#'@param omega_hat_11 covariance matrix decomposition of the fixed effects
#'@param omega_hat_21 covariance matrix decomposition of the covariance between fixed and random effects
#'@param omega_hat_22 covariance matrix decomposition of the random effects
#'@param psi_hat fixed effects
#'@param psi initial values or previous MCMC sample of fixed effects
#'@param Sigma covariance matrix of the random effects
UpdateDelta <- function(q, p, K, beta_hat, Mu, omega_hat_11, omega_hat_21, omega_hat_22, psi_hat, psi, Sigma) {
    .Call(`_remx_UpdateDelta`, q, p, K, beta_hat, Mu, omega_hat_11, omega_hat_21, omega_hat_22, psi_hat, psi, Sigma)
}

#'UpdateDeltaInd
#'
#'@param p number of random effects
#'@param K number of networks
#'@param beta_hat MLE estimates
#'@param omega_hat_22 covariance matrix of the random effects
#'@param Mu random effects mean
#'@param Sigma covariance matrix of the random effects
UpdateDeltaInd <- function(p, K, beta_hat, omega_hat_22, Mu, Sigma) {
    .Call(`_remx_UpdateDeltaInd`, p, K, beta_hat, omega_hat_22, Mu, Sigma)
}

#' sampler
#'
#' A function that runs the Gibbs sampler for a tie-oriented mixed-effect relational event model
#'
#' @param Niter number of iterations to run the Gibbs sampler
#' @param Nchain number of MCMC chains
#' @param NburnIn number of samples to discard at the beginning of every chain
#' @param Nthin number of samples to skip for every MCMC sample kept
#' @param p number of random effects in the model
#' @param q number of fixed effects in the model
#' @param K number of groups (or networks) in the multilevel analysis
#' @param delta a 3-d array with dimension p x K x Nchain containing the starting values for the random effects parameters
#' @param beta_hat a matrix with dimensions p X K containing the MLEs of the random effects estimated from the independent networks
#' @param omega_hat a 3-d array with dimensions p x p x K containing the covariance matrices of the MLEs estimated from the independent groups
#' @param omega_hat_11 covariance matrix decomposition of the fixed effects
#' @param omega_hat_21 covariance matrix decomposition of the covariance between fixed and random effects
#' @param omega_hat_22 covariance matrix decomposition of the random effects
#' @param Mu a matrix with dimensions Nchain x p containing the initial values for the random-effect means
#' @param Sigma a 3-d array with dimensions p x p x Nchain containing the initial values for the random-effect covariance matrix
#' @param eta an integer that we set equal to 2, so the covariances have an uniform prior, see Huang & Wand (2013)
#' @param Lambda a matrix with dimensions Nchain x p containing initial values for the Lambda parameter
#' @param xi a scalar that can be an arbitrarily large number, see Gelman (2006)
#' @param SigmaMean a matrix with dimensions q x K representing the standard errors of the MLEs for the fixed effects
#' @param psi a matrix with dimensions q x K representing the MLEs for the fixed effects independently estimated from every group
#' @param psi_hat a matrix with dimensions q x K representing the MLEs for the fixed effects independently estimated from every group
#' @param random_effect a matrix with 1's and 0's
#' @param fixed_effect a matrix with 1's and 0's
#' @param randomModel a boolean, if equals to TRUE it states that the model contain only random effects
#'
#' @return a list containing the MCMC samples for all parameters in the model
#'
sampler <- function(Niter, Nchain, NburnIn, Nthin, p, q, K, delta, beta_hat, omega_hat, omega_hat_11, omega_hat_21, omega_hat_22, Mu, Sigma, eta, Lambda, xi, SigmaMean, psi, psi_hat, random_effect, fixed_effect, randomModel) {
    .Call(`_remx_sampler`, Niter, Nchain, NburnIn, Nthin, p, q, K, delta, beta_hat, omega_hat, omega_hat_11, omega_hat_21, omega_hat_22, Mu, Sigma, eta, Lambda, xi, SigmaMean, psi, psi_hat, random_effect, fixed_effect, randomModel)
}

#' samplerActor
#'
#' A function that runs the Gibbs sampler for the DyNaM (actor-oriented) mixed-effect relational event model
#'
#' @param Niter number of iterations to run the Gibbs sampler
#' @param Nchain number of MCMC chains
#' @param NburnIn number of samples to discard at the beginning of every chain
#' @param Nthin number of samples to skip for every MCMC sample kept
#' @param v an integer representing the number of random effects in the receiver model
#' @param u an integer representing the number of fixed effects in the receiver model
#' @param K number of groups (or networks) in the multilevel analysis
#' @param beta a 3-d array with dimension v x K x Nchain containing the starting values for the random effects parameters in the receiver model
#' @param beta_hat a matrix with dimensions v X K containing the MLEs of the random effects in the receiver model estimated from the independent networks
#' @param omega_hat a 3-d array with dimensions v x v x K containing the covariance matrices of the MLEs for the random effects in the receiver model estimated from the independent groups
#' @param omega_hat_11 covariance matrix decomposition of the fixed effects
#' @param omega_hat_21 covariance matrix decomposition of the covariance between fixed and random effects
#' @param omega_hat_22 covariance matrix decomposition of the random effects
#' @param MuB a matrix with dimensions v x Nchain containing the initial values of the random-effect means in the receiver model
#' @param Sigma a 3-d array with dimensions v x v x Nchain containing the initial values for the covariance matrix of the random-effects in the receiver model
#' @param eta an integer that we set equal to 2, so the covariances have an uniform prior, see Huang & Wand (2013)
#' @param LambdaB a matrix with dimensions Nchain x v containing initial values for the Lambda parameter in the receiver model
#' @param xi a scalar that can be an arbitrarily large number, see Gelman (2006)
#' @param SigmaPsi a matrix with dimensions u x K representing the standard errors of the MLEs for the fixed effects in the receiver model
#' @param psi a matrix with dimensions u x K representing the MLEs for the fixed effects in the receiver model independently estimated from every group
#' @param psi_hat a matrix with dimensions u x K representing the MLEs for the fixed effects in the receiver model independently estimated from every group
#' @param p an integer representing the number of random effects in the sender model
#' @param q an integer representing the number of fixed effects in the sender model
#' @param gamma a 3-d array with dimension p x K x Nchain containing the starting values for the random effects parameters in the sender
#' @param gamma_hat a matrix with dimensions p X K containing the MLEs of the random effects in the sender model estimated from the independent networks
#' @param zeta_hat a 3-d array with dimensions p x p x K containing the covariance matrices of the MLEs for the random effects in the sender model estimated from the independent groups
#' @param zeta_hat_11 covariance matrix decomposition of the fixed effects
#' @param zeta_hat_21 covariance matrix decomposition of the covariance between fixed and random effects
#' @param zeta_hat_22 covariance matrix decomposition of the random effects
#' @param MuG a matrix with dimensions p x Nchain containing the initial values of the random-effect means in the sender model
#' @param Zeta a 3-d array with dimensions p x p x Nchain containing the initial values for the covariance matrix of the random-effects in the sender model
#' @param LambdaG a matrix with dimensions Nchain x p containing initial values for the Lambda parameter in the sender model
#' @param SigmaPhi a matrix with dimensions q x K representing the standard errors of the MLEs for hte fixed effects in the sender model
#' @param phi a matrix with dimensions q x K representing the MLEs for the fixed effects in the sender model independently estimated from every group
#' @param phi_hat a matrix with dimensions q x K representing the MLEs for the fixed effects in the sender model independently estimated from every group
#' @param random_effect_rec matrix with 0's and 1's
#' @param fixed_effect_rec matrix with 0's and 1's
#' @param random_effect_snd matrix with 0's and 1's
#' @param fixed_effect_snd matrix with 0's and 1's
#' @param randomModelSnd a boolean, if equals to TRUE it states that the sender model contain only random effects
#' @param randomModelRec a boolean, if equals to TRUE it states that the receiver model contain only random effects
#'
#' @return a list containing two other lists with the MCMC sample for all parameters in the sender and receiver models
#'
samplerActor <- function(Niter, Nchain, NburnIn, Nthin, v, u, K, beta, beta_hat, omega_hat, omega_hat_11, omega_hat_21, omega_hat_22, MuB, Sigma, eta, LambdaB, xi, SigmaPsi, psi, psi_hat, p, q, gamma, gamma_hat, zeta_hat, zeta_hat_11, zeta_hat_21, zeta_hat_22, MuG, Zeta, LambdaG, SigmaPhi, phi, phi_hat, random_effect_rec, fixed_effect_rec, random_effect_snd, fixed_effect_snd, randomModelSnd, randomModelRec) {
    .Call(`_remx_samplerActor`, Niter, Nchain, NburnIn, Nthin, v, u, K, beta, beta_hat, omega_hat, omega_hat_11, omega_hat_21, omega_hat_22, MuB, Sigma, eta, LambdaB, xi, SigmaPsi, psi, psi_hat, p, q, gamma, gamma_hat, zeta_hat, zeta_hat_11, zeta_hat_21, zeta_hat_22, MuG, Zeta, LambdaG, SigmaPhi, phi, phi_hat, random_effect_rec, fixed_effect_rec, random_effect_snd, fixed_effect_snd, randomModelSnd, randomModelRec)
}

